name: process-on-chain-events-cron
on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our sqs consumer api to process new on chain events
        run: |
          curl --request POST \
          --url 'https://nft-pawn-shop-rinkeby.vercel.app/api/cron/processNewOnchainEvents' \
          --header 'Authorization: Bearer ${{ secrets.NOTIFICATIONS_CRON_API_SECRET_KEY }}'